[package]
name = "game_of_life_core"
version = "0.1.0"
edition = "2021"

[dependencies]
modular-bitfield = "0.11.2"
rand = { version = "0.8.5", optional = true }

[[example]]
name = "std_print_universe"
required-features = ["rand"]
